app/models/FacturaVentas.py
from flask_login import UserMixin
from app import db
from app.models.Clientes import Clientes
from app.models.Productos import Productos
from datetime import datetime

class FacturaVentas(db.Model, UserMixin):
    __tablename__ = "facturaVenta"
    idFacturaVentas = db.Column(db.Integer, primary_key=True)
    idClientes = db.Column(db.Integer, db.ForeignKey('cliente.idClientes'), nullable=False)
    horaFacturaVentas = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    totalFacturaVentas = db.Column(db.Integer, nullable=False)
    productos = db.relationship("Productos", secondary="detalleVenta",back_populates="facturas")
    

  

app/routes/clienteRoute.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.Clientes import Clientes, db
from flask_bcrypt import Bcrypt

bp = Blueprint('clientes', __name__)

@bp.route('/cliente')
def index():
    data = Clientes.query.all()
    return render_template('clientes/index.html', data=data)

@bp.route('/clientes/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':       
        bcrypt=Bcrypt()
        nombreClientes = request.form['nombreClientes']
        cedulaClientes = request.form['cedulaClientes']
        correoClientes = request.form['correoClientes']   
        password =request.form['password'] 
        hashedpassword = bcrypt.generate_password_hash(password).decode('utf-8')
    
        new_Clientes = Clientes(nombreClientes=nombreClientes, cedulaClientes=cedulaClientes, correoClientes=correoClientes, password=hashedpassword)
        db.session.add(new_Clientes)
        db.session.commit()
        
        return redirect(url_for('clientes.index'))

    return render_template('clientes/add.html')

@bp.route('/clientes/edit/<int:idClientes>', methods=['GET', 'POST'])
def edit(idClientes):
    clientes = Clientes.query.get_or_404(idClientes)

    if request.method == 'POST':

        clientes.nombreClientes = request.form['nombreClientes']
        clientes.cedulaClientes = request.form['cedulaClientes']
        clientes.correoClientes = request.form['correoClientes']
        db.session.commit()
        return redirect(url_for('clientes.index'))

    return render_template('clientes/edit.html', clientes=clientes)


@bp.route('/Clientes/delete/<int:idClientes>')
def delete(idClientes):
    cliente = Clientes.query.get_or_404(idClientes)
    
    db.session.delete(cliente)
    db.session.commit()

    return redirect(url_for('clientes.index'))

app/templates/facturaVentas/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> bienvenido a facturaVenta</h1>
    
        <table>
            <tr>
                <th>idFactutaVenta</th>
                <th>horaFacturaVenta</th>
                <th>totalFacturaVenta</th>
            
            </tr>
            {% for FacturaVentas in data %}
            <tr>
                <td>{{ FacturaVentas.idFacturaVenta }}</td>
                <td>{{ FacturaVentas.horaFacturaVenta }}</td>
                <td>{{ FacturaVentas.totalFacturaVentas }}</td>
                <td>
                    <a href="{{ url_for('clientes.edit', idClientes=cliente.idClientes) }}">Editar</a>
                    <a href="{{ url_for('clientes.delete', idClientes=cliente.idClientes) }}">Eliminar</a>
                    
                </td>
            </tr>
            {% endfor %}
        </table>
        <a href="{{ url_for('clientes.add') }}">Agregar clientes</a>
        <br>
        <a href="{{ url_for('productos.index') }}">Ir a productos</a>
    </div>
    
</body>
</html>

app/templates/facturaVentas/vistaFactura.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/facturaVenta.css')}}">
    <title>Document</title>
</head>

<body>
    <div class="contenedorFactura">
        <div class="header">
            <img src="{{ url_for('static', filename='imagenes/logo.jpg') }}" alt="logo">
            <h1>Factura de Venta</h1>
        </div>

        <div class="informacionCliente">
            <p><strong>Cliente:</strong> {{current_user.nombreClientes}}</p>
            <p><strong>Cedula:</strong> {{current_user.cedulaClientes}}</p>
            <p><strong>Fecha:</strong> {{ fecha}}</p>
        </div>

        <h2>Productos:</h2>
        <div class="contenedorProductos">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">idProductos</th>
                        <th scope="col">Descripcion Productos</th>
                        <th scope="col">Precio Productos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for Detalles in Detalles %}
                        <tr>
                            <td scope="row">{{ Detalles.producto.idProductos }}</td>
                            <td scope="row">{{ Detalles.producto.descripcionProductos }}</td>
                            <td scope="row">{{ Detalles.producto.precioProductos }}</td>
                        </tr>
                    {% endfor %}

                    <tr>
                        <td></td>
                        <th>subTotal:</th>
                        <th>{{ subTotal }}</th>
                    </tr>

                    <tr>
                        <td></td>
                        <th>Iva-19%:</th>
                        <th>{{ iva }}</th>
                    </tr>

                    <tr>
                        <td></td>
                        <th>Total:</th>
                        <th>{{ total }}</th>
                    </tr>
                </tbody>
            </table>
        </div>

        <p class="irAProducto">
            <br>
            <a href="{{ url_for('carritos.vistaProductos') }}">Ir A Prodcutos</a>
        </p>

        <div class="mensaje">
            <p>
                Gracias por elegir nuestros productos/servicios. Valoramos tu preferencia y esperamos verte nuevamente
                pronto; ¡Que tengas un excelente día!.
            </p>
        </div>
    
    </div>
</body>
<script>

</script>

</html>