app/models/Productos.py
from app import db

class Productos(db.Model):
    __tablename__ = "producto"
    idProductos = db.Column(db.Integer, primary_key=True)
    descripcionProductos= db.Column(db.String(255), nullable=False)
    precioProductos = db.Column(db.String(255),nullable=False)
    cantidadProductos = db.Column(db.String(255), nullable=False)
    nombreImagen = db.Column(db.String(255))
    informacionProductos = db.Column(db.String(3000),nullable=True)
    facturas = db.relationship("FacturaVentas", secondary="detalleVenta",back_populates="productos")
    

app/routes/facturaVentasRoute.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.FacturaVentas import FacturaVentas, db
from datetime import datetime
from app.routes.carritoVentasRoute import carritoVentas
from app.models.Clientes import Clientes
from app.models.Productos import Productos
from flask_login import current_user
from app.models.DetalleVenta import DetalleVentas

bp = Blueprint('facturaVentas', __name__)
Productos=Productos
@bp.route('/facturaVenta')
def index():
    

    if current_user.is_authenticated:
        fechaActual = datetime.now()
        fechaFormateada = fechaActual.strftime("%Y-%m-%d")

        subTotal = 0
        for carritoP in carritoVentas.getItems():
            subTotal +=  int(carritoP['producto'].precioProductos)
            print("subtotal",subTotal)

        iva = subTotal * 0.19
        subTotalFinal = iva + subTotal
        
        horaActual = datetime.now()
        formatoHora = horaActual.strftime("%H:%M:%S")
        print(formatoHora)

        
        new_FacturaVenta = FacturaVentas(
        idFacturaVentas=None,
        idClientes=current_user.idClientes,
        horaFacturaVentas=horaActual,
        totalFacturaVentas=subTotalFinal
        )
                
        db.session.add(new_FacturaVenta)
        db.session.commit()

        for carrito in carritoVentas.getItems():
            idProductos = carrito["producto"].idProductos      
            detallefactura = DetalleVentas(idDetalleVenta=None,cantidadDetalleVenta=1,idFactura=new_FacturaVenta.idFacturaVentas,idClientes=current_user.idClientes, idProductos=idProductos)
            db.session.add(detallefactura)
            db.session.commit() 
        #carritoVentas.vaciarcarrito()
            
        Detalles =DetalleVentas.query.filter_by(idFactura=new_FacturaVenta.idFacturaVentas).all()

        carritoVentas.vaciarcarrito()
        return render_template('facturaVentas/vistaFactura.html', fecha=fechaFormateada, hora=formatoHora,subTotal=subTotal, total=subTotalFinal,iva=iva,Detalles=Detalles)

    return redirect(url_for('carritos.eliminarDelCarrito'))


    

app/routes/productoRoute.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.Productos import Productos
from app.models.Clientes import Clientes, db


bp = Blueprint('productos', __name__)

@bp.route('/productos'  , methods=['GET', 'POST'])
def index():
    data = Productos.query.all()
    return render_template('productos/index.html', data=data)


@bp.route('/productos/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        descripcionProductos = request.form['descripcionProductos']
        precioProductos = request.form['precioProductos']
        cantidadProductos = request.form['cantidadProductos']
        nombreImagen = request.form['nombreImagen']
        informacionProductos = request.form['informacionProductos']
        
        new_Producto = Productos(descripcionProductos=descripcionProductos, precioProductos=precioProductos, cantidadProductos=cantidadProductos, nombreImagen=nombreImagen, informacionProductos=informacionProductos)
        db.session.add(new_Producto)
        db.session.commit()
        
        return redirect(url_for('productos.index'))
    data = Productos.query.all()
    return render_template('productos/add.html', data=data)

@bp.route('/productos/edit/<int:idProductos>', methods=['GET', 'POST'])
def edit(idProductos):
    print(f"El valor es: {idProductos}")
    data = Productos.query.get_or_404(idProductos)
    #print(f"El producto es: {data}")

    if request.method == 'POST':
        data.descripcionProductos = request.form['descripcionProductos']
        data.precioProductos = request.form['precioProductos']
        data.cantidadProductos = request.form['cantidadProductos']
        db.session.commit()
        
        return redirect(url_for('productos.index'))
    return render_template('productos/edit.html', data=data)

@bp.route('/productos/delete/<int:idProductos>')
def delete(idProductos):
    productos = Productos.query.get_or_404(idProductos)
    
    db.session.delete(productos)
    db.session.commit()

    return redirect(url_for('productos.index'))

app/templates/productos/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/productosAdd.css')}}">
    <title>Agregar clientes</title>
</head>
<body>
    <div>
        <h1>Agregar productos</h1>
        <form action="{{ url_for('productos.add') }}" method="post">
            <label for="descripcionProductos">descripcion Productos:</label>
            <input type="text" id="descripcionProductos" name="descripcionProductos"required>
            <label for="precioProductos">precio Productos:</label>
            <input type="text" id="precioProductos" name="precioProductos"required>
            <label for="cantidadProductos">cantidad Productos:</label>
            <input type="text" id="cantidadProductos" name="cantidadProductos"required>
            <label for="nombreImagen">nombre de la imagen:</label>
            <input type="text" id="nombreImagen" name="nombreImagen" required>
            <label for="informacionProductos">informacion Productos:</label>
            <input type="text" id="informacionProductos" name="informacionProductos"required>

            
            <button type="submit">Agregar producto</button>
        </form>
    </div>
</body>
</html>

app/templates/productos/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/productosEdit.css')}}">
    <title>Editar Libro</title>
</head>

<body>
    <div>
        <h1>Editar producto</h1>
        <form action="{{ url_for('productos.edit', idProductos = data.idProductos) }}" method="post">
            <label for="descripcionProductos">descripcion Productos:</label>
            <input type="text" id="descripcionProductos" name="descripcionProductos"
                value="{{ data.descripcionProductos }}" required>
            <label for="precioProductos">precio Productos:</label>
            <input type="text" id="precioProductos" name="precioProductos" value="{{ data.precioProductos}}" required>
            <label for="cantidadProductos">cantidad Productos:</label>
            <input type="text" id="cantidadProductos" name="cantidadProductos" value="{{ data.cantidadProductos }}"
                required>
            <button type="submit">Actualizar Productos</button>
        </form>
    </div>
</body>

</html>

app/templates/productos/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/productosIndex.css')}}">

    <title>Document</title>
</head>

<body>
    <div>
        <h1>Lista de Productos</h1>
        <table>
            <tr>
                <th>idProductos</th>
                <th>descripcionProductos</th>
                <th>precioProductos</th>
                <th>cantidadProductos</th>
            </tr>
            {% for producto in data %}
            <tr>
                <td>{{ producto.idProductos }}</td>
                <td>{{ producto.descripcionProductos }}</td>
                <td>{{ producto.precioProductos }}</td>
                <td>{{ producto.cantidadProductos }}</td>
                <td>
                    <a href="{{ url_for('productos.edit', idProductos=producto.idProductos) }}">Editar</a>
                    <a href="{{ url_for('productos.delete', idProductos=producto.idProductos) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
            {% endfor %}
        </table>
        <a href="{{ url_for('productos.add') }}">Agregar producto</a>
        <br>
        <a href="{{ url_for('clientes.index') }}">Ir a clientes</a>
        <br>
        <a href="{{ url_for('autentificacionBp.dashboard') }}">Ir A Dashboard</a>
    </div>
</body>

</html>

app/templates/productos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Autor</title>
</head>
<body>
    <h1>Carrito</h1>
    <table>
        <tr>
            <th>descripcionProductos</th>
            <th>precioProductos</th>
            <th>cantidadProductos</th>
            <th>Acciones</th>
        </tr>
        {% for item in items %}
        
            <tr>
                <td>{{ item['producto'].nombreproducto }}</td>
                <td>{{ item['producto'].precioproducto }}</td>
                <td>{{ item['cantidad'] }}</td>
                <td>
                    Acciones               
                    <a href="{{ url_for('eliminarProducto', idProductos=item['producto'].idProductos) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}        
    </table>
    <a href="{{ url_for('facturaVentas.add') }}">Generar factura</a>
</body>
</html>