app/models/carritoVentas.py
from app.models.Productos import Productos

class CarritoVentas:
    def __init__(self):
        self.carrito = [] # en este caso se iniicializa carrito como una lista vacia#


    def agregarProducto(self, idProductos, cantidadProductos):
        producto = Productos.query.get(idProductos)
        if producto:
            item = {'producto': producto, 'cantidad': cantidadProductos}
            self.carrito.append(item) # con el metodo append se agreaga los datos que contien el diccionario a la base de datos#

    def calcularTotal(self):
        return sum(item['producto'].precioproductos * item['cantidadProductos'] for item in self.carrito)
    
    def tamanoD(self):   
        return len(self.carrito)

    def getItems(self):
        return self.carrito
    
    def vaciarcarrito(self):
        self.carrito = []
        
    def eliminarProducto(self, idProductos):
     # Buscar el índice del producto con el id dado en el carrito
        indexProducto = next((index for index, item in enumerate(self.carrito) if item['producto'].idProductos == idProductos), None)

        if indexProducto is not None:
        # Eliminar el producto del carrito usando el índice encontrado
         productoEliminado = self.carrito.pop(indexProducto)
         print(f"El producto con id {idProductos} ({productoEliminado['producto'].descripcionProductos}) ha sido eliminado del carrito.")
        else:
         print(f"El producto con id {idProductos} no está en el carrito.")
         
         
    def calcularTotal(self):
      return sum(item['producto'].precioProductos * item['cantidad'] for item in self.carrito)

app/routes/carritoVentasRoute.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from app.models.Productos import Productos
from app.models.carritoVentas import CarritoVentas

bp = Blueprint('carritos', __name__)

carritoVentas = CarritoVentas()

@bp.route('/')
def vistaProductos():
    data = Productos.query.all()
    print(carritoVentas.getItems())  
    tamano = tCarrito()  
    return render_template('index.html', data=data, tamano=tamano)

@bp.route('/ListarCarrito')
def listar():
    items = carritoVentas.getItems()
    return render_template('productos/list.html', items=items)

@bp.route('/ListarProductos')
def index():
 subTotal = 0
 for carritoP in carritoVentas.getItems():
   subTotal +=  int(carritoP['producto'].precioProductos)
   print("subtotal",subTotal)
 return render_template('carrito/carritoVentas.html',carritoVentas=carritoVentas.getItems(),subTotal=subTotal)

@bp.route('/agregar/<int:idProductos>', methods=['POST'])
def agregarAlCarrito(idProductos):
    cantidad = 1
    carritoVentas.agregarProducto(idProductos, cantidad)
    return redirect(url_for('carritos.vistaProductos'))
    

@bp.route('/realizarCompra')
def realizarCompra():
    total = carritoVentas.calcularTotal()
    return render_template('realizarCompra.html', total=total)

@bp.route('/generarFactura', methods=['POST'])
def generarFactura():
    total = carritoVentas.calcularTotal()
    # Aquí puedes almacenar la información en la base de datos (crear registros en Carrito y Factura)
    # y luego limpiar el carrito de compras
    carritoVentas.carrito = []
    return render_template('factura.html', total=total) #debo mirar bien a donde voy a direccionar

@bp.route('/itemscarrito', methods=['GET', 'POST'])
def tCarrito():
    a = carritoVentas.tamanoD()
    return a

@bp.route('/eliminar/<int:idProductos>', methods=['GET', 'POST'])
def eliminarDelCarrito(idProductos):
    global subTotal
    print(idProductos)
    carritoVentas.eliminarProducto(idProductos)
    subTotal = 0  # Inicializa el subtotal antes de recalcularlo
    for carritoP in carritoVentas.getItems():
        subTotal += int(carritoP['producto'].precioProductos)
    print("subtotal", subTotal)
    return render_template('carrito/carritoVentas.html', idProductos=idProductos, carritoVentas=carritoVentas.getItems(), subTotal=subTotal)

@bp.route('/vaciarCarrito/<int:idProductos>',methods=['GET', 'POST'])
def vaciarcarrito(idProductos):
    carritoVaciado = carritoVentas.query.get(idProductos)
    
    if carritoVaciado:
        carritoVaciado.vaciarcarrito()
        flash('carrito vaciado correctamente', 'success')
        return render_template('index.html')
    else: flash('no se encontro el producto en el carrito', 'danger')

app/routes/facturaVentasRoute.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.FacturaVentas import FacturaVentas, db
from datetime import datetime
from app.routes.carritoVentasRoute import carritoVentas
from app.models.Clientes import Clientes
from app.models.Productos import Productos
from flask_login import current_user
from app.models.DetalleVenta import DetalleVentas

bp = Blueprint('facturaVentas', __name__)
Productos=Productos
@bp.route('/facturaVenta')
def index():
    

    if current_user.is_authenticated:
        fechaActual = datetime.now()
        fechaFormateada = fechaActual.strftime("%Y-%m-%d")

        subTotal = 0
        for carritoP in carritoVentas.getItems():
            subTotal +=  int(carritoP['producto'].precioProductos)
            print("subtotal",subTotal)

        iva = subTotal * 0.19
        subTotalFinal = iva + subTotal
        
        horaActual = datetime.now()
        formatoHora = horaActual.strftime("%H:%M:%S")
        print(formatoHora)

        
        new_FacturaVenta = FacturaVentas(
        idFacturaVentas=None,
        idClientes=current_user.idClientes,
        horaFacturaVentas=horaActual,
        totalFacturaVentas=subTotalFinal
        )
                
        db.session.add(new_FacturaVenta)
        db.session.commit()

        for carrito in carritoVentas.getItems():
            idProductos = carrito["producto"].idProductos      
            detallefactura = DetalleVentas(idDetalleVenta=None,cantidadDetalleVenta=1,idFactura=new_FacturaVenta.idFacturaVentas,idClientes=current_user.idClientes, idProductos=idProductos)
            db.session.add(detallefactura)
            db.session.commit() 
        #carritoVentas.vaciarcarrito()
            
        Detalles =DetalleVentas.query.filter_by(idFactura=new_FacturaVenta.idFacturaVentas).all()

        carritoVentas.vaciarcarrito()
        return render_template('facturaVentas/vistaFactura.html', fecha=fechaFormateada, hora=formatoHora,subTotal=subTotal, total=subTotalFinal,iva=iva,Detalles=Detalles)

    return redirect(url_for('carritos.eliminarDelCarrito'))


    

app/templates/carrito/carritoVentas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estiloCarrito.css')}}">

    <title>Carrito de Compras</title>
    
</head>

<body>
    <div>
        <h1>Carrito de Compras</h1>

        {% for producto in carritoVentas %}
            <form action="{{ url_for('carritos.eliminarDelCarrito', idProductos=producto['producto'].idProductos) }}" method="post" class="card">
                <div class="contenedorImagen">
                    <img src="{{ url_for('static', filename='imagenes/' ~ producto['producto'].nombreImagen) }}">
                </div>
                <div class="card-title">{{ producto['producto'].descripcionProductos }}</div>
                <div class="card-description">{{ producto['producto'].informacionProductos }}</div>
                <div class="card-price">{{ producto['producto'].precioProductos }}</div>
                <div class="subtotal">precio: {{ producto['producto'].precioProductos }}</div>
            
            <!-- Agregar un botón de tipo submit para eliminar el producto -->
            <button type="submit" class="eliminar-boton">Eliminar producto</button>
            </form>
        {% endfor %}

        <p class="total">subTotal: {{ subTotal }}</p>


        
        </div>

        <!-- Agrega más tarjetas según sea necesario -->

        <p class="total">subTotal:{{subTotal}}</p>

        <a  class="boton-comprar"href="{{ url_for('facturaVentas.index') }}">Generar Factura</a>

    
    
    </div>
    
</body>

</html>

app/templates/carrito/realizarCompra.html
<!-- templates/realizar_compra.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Realizar Compra</title>
</head>
<body>
    <h1>Realizar Compra</h1>
    <form action="/generarFactura" method="post">
        <p>Total a pagar: ${{ total }}</p>
        <button type="submit">Generar Factura</button>
    </form>
</body>
</html>