app/routes/autentificacionRoute.py
import bcrypt
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from flask_wtf import FlaskForm
from werkzeug.security import check_password_hash
from wtforms import SubmitField
from wtforms import StringField, PasswordField ,validators
from flask_bcrypt import Bcrypt
from app.models.Clientes import Clientes


from app import db
# carritoVentas = CarritoVentas()

bp = Blueprint('autentificacionBp', __name__)

from flask import redirect, url_for, flash
bcrypt = Bcrypt()


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        if 'correoClientes' in request.form:
            correoClientes = request.form['correoClientes']
        else:   flash("correo no coincide") 
         
        password = request.form['password']
        
        cliente = Clientes.query.filter_by(correoClientes=correoClientes).first()
        
        if cliente:
            clientePasswordBd = cliente.password
            if bcrypt.check_password_hash(clientePasswordBd, password):
                login_user(cliente)
                flash("Login successful!", "success")
                
                  # Verifica el rol y redirige según el rol
                if cliente.rol == 'administrador':
                    return redirect(url_for('autentificacionBp.dashboard'))
                else:
                    return redirect(url_for('carritos.vistaProductos'))
            else:
                flash("Invalid password. Please try again.", "error")
        else:
            flash("User not found. Please try again.", "error")

    if current_user.is_authenticated:
        return render_template('clientes/index.html')
    else:
        return render_template('autentificacion/login.html')

@bp.route('/registro', methods=['GET', 'POST'])
def registro():
    if request.method == 'POST':
        nombreclientes = request.form['nombreClientes']
        cedulaclientes = request.form['cedulaClientes']
        correoclientes = request.form['correoClientes']
        password = request.form['password']
        print("Antes de imprir el pass")
        print(password)
        # Verificar si el usuario ya existe
        if Clientes.query.filter_by(nombreClientes=nombreclientes).first():
            flash("El usuario ya existe. Por favor, elige otro nombre de usuario.", "error")
            return redirect(url_for('autentificacionBp.registro'))

        # Crear una nueva cuenta
        
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
        nuevo_cliente = Clientes(
            nombreClientes=nombreclientes,
            cedulaClientes=cedulaclientes,
            correoClientes=correoclientes,
            password=hashed_password,
            rol='usuario'  # Establece el rol por defecto al registrar un nuevo cliente

        )

        # Agregar el nuevo cliente a la base de datos
        db.session.add(nuevo_cliente)
        db.session.commit()

        flash("Cuenta creada con éxito. Ahora puedes iniciar sesión.", "success")
        print("antes de direccionar al login")
        return redirect(url_for('autentificacionBp.login'))

    return render_template("autentificacion/registro.html")

         

@bp.route('/dashboard')
@login_required
def dashboard():
    data = Clientes.query.all()

    if current_user.rol == 'administrador':
        return render_template('administrador/dashboard.html', data=data)  
    else:
        user_name = current_user.nombreClientes
        return f'Welcome, {user_name}! This is your dashboard.'

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('carritos.vistaProductos'))

app/routes/carritoVentasRoute.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from app.models.Productos import Productos
from app.models.carritoVentas import CarritoVentas

bp = Blueprint('carritos', __name__)

carritoVentas = CarritoVentas()

@bp.route('/')
def vistaProductos():
    data = Productos.query.all()
    print(carritoVentas.getItems())  
    tamano = tCarrito()  
    return render_template('index.html', data=data, tamano=tamano)

@bp.route('/ListarCarrito')
def listar():
    items = carritoVentas.getItems()
    return render_template('productos/list.html', items=items)

@bp.route('/ListarProductos')
def index():
 subTotal = 0
 for carritoP in carritoVentas.getItems():
   subTotal +=  int(carritoP['producto'].precioProductos)
   print("subtotal",subTotal)
 return render_template('carrito/carritoVentas.html',carritoVentas=carritoVentas.getItems(),subTotal=subTotal)

@bp.route('/agregar/<int:idProductos>', methods=['POST'])
def agregarAlCarrito(idProductos):
    cantidad = 1
    carritoVentas.agregarProducto(idProductos, cantidad)
    return redirect(url_for('carritos.vistaProductos'))
    

@bp.route('/realizarCompra')
def realizarCompra():
    total = carritoVentas.calcularTotal()
    return render_template('realizarCompra.html', total=total)

@bp.route('/generarFactura', methods=['POST'])
def generarFactura():
    total = carritoVentas.calcularTotal()
    # Aquí puedes almacenar la información en la base de datos (crear registros en Carrito y Factura)
    # y luego limpiar el carrito de compras
    carritoVentas.carrito = []
    return render_template('factura.html', total=total) #debo mirar bien a donde voy a direccionar

@bp.route('/itemscarrito', methods=['GET', 'POST'])
def tCarrito():
    a = carritoVentas.tamanoD()
    return a

@bp.route('/eliminar/<int:idProductos>', methods=['GET', 'POST'])
def eliminarDelCarrito(idProductos):
    global subTotal
    print(idProductos)
    carritoVentas.eliminarProducto(idProductos)
    subTotal = 0  # Inicializa el subtotal antes de recalcularlo
    for carritoP in carritoVentas.getItems():
        subTotal += int(carritoP['producto'].precioProductos)
    print("subtotal", subTotal)
    return render_template('carrito/carritoVentas.html', idProductos=idProductos, carritoVentas=carritoVentas.getItems(), subTotal=subTotal)

@bp.route('/vaciarCarrito/<int:idProductos>',methods=['GET', 'POST'])
def vaciarcarrito(idProductos):
    carritoVaciado = carritoVentas.query.get(idProductos)
    
    if carritoVaciado:
        carritoVaciado.vaciarcarrito()
        flash('carrito vaciado correctamente', 'success')
        return render_template('index.html')
    else: flash('no se encontro el producto en el carrito', 'danger')

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estiloIndex.css') }}">

    <title>Document</title>
</head>

<body>
    <header id="header">
        <h1>BiciMotos Tienda Deportiva</h1>
        <a href="#">
            <a href="{{ url_for('carritos.index') }}" class="contenedor-imagen">
                
                <h3 id="texto-superpuesto">
                    {{ tamano }}
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                        <path
                            d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0" />
                    </svg>
                    
                </h3>
            </a>

            {% if current_user.is_authenticated %}
            {{ current_user.nombreClientes }}

            <a href="{{ url_for('autentificacionBp.logout') }}">cerrar Session</a>
            {% else %}
            <a href="{{ url_for('autentificacionBp.login') }}">Iniciar Session</a>

        </a>
        {% endif %}
    </header>

    <div class="contenedor" id="contenedor">
        {% for elProducto in data %}
        <div class="box">
            
            <form action="/agregar/{{ elProducto.idProductos }}" method="post">
                <img src="{{ url_for('static', filename='imagenes/' ~ elProducto.nombreImagen) }}" alt="{{ elProducto.nombreImagen }}">
                <div class="centrarInformacion">
                    <input type="hidden" name="idProducto" value="{{ elProducto.idProductos }}">
                    <input type="hidden" name="informacionProductos" id="informacionProductos" value="{{ elProducto.descripcionProductos }}">
                    <p class="producto" name="producto" value="">{{ elProducto.descripcionProductos }}</p>
                    <input type="hidden" name="precioProducto" id="precioProducto" value="{{ elProducto.precioProductos }}">
                    <p class="producto" name="producto" value=""> {{ elProducto.precioProductos }}</p>
                    {% if current_user.is_authenticated %}
                    <button class="btcontar" type="submit" name="accion" value="insertar">Agregar</button>
                    {%else%}
                    <a style="color: black;" href="{{ url_for('autentificacionBp.login') }}">Agregar</a>
                    {% endif %}
                </div>
            </form>
            
        </div>
        {% endfor %}
    </div>


</body>


</html>